// ============================================================
// Company OS — Predefined Theme Palettes
// ============================================================

import { ThemeConfig } from '@/types/theme';

export const themes: ThemeConfig[] = [
  // ── 1. Metallic Dark (DEFAULT) ────────────────────────────
  {
    id: 'metallic-dark',
    name: 'Metallic Dark',
    description: 'Premium graphite + silver',
    mode: 'dark',
    colors: {
      background: '#0F1115',
      foreground: '#F4F5F7',
      surface: '#171A20',
      surfaceElevated: '#1E222A',
      border: '#343943',
      input: '#1E222A',
      ring: '#B8BDC7',
      primary: '#B8BDC7',
      primaryForeground: '#0F1115',
      secondary: '#7F8794',
      secondaryForeground: '#F4F5F7',
      muted: '#1E222A',
      mutedForeground: '#707782',
      accent: '#1E222A',
      accentForeground: '#E2E5EA',
      card: '#171A20',
      cardForeground: '#F4F5F7',
      popover: '#171A20',
      popoverForeground: '#F4F5F7',
      success: '#4CAF7D',
      successForeground: '#FFFFFF',
      warning: '#D6A84F',
      warningForeground: '#FFFFFF',
      danger: '#D66B6B',
      dangerForeground: '#FFFFFF',
      info: '#6D9ED8',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 2. Metallic Silver ────────────────────────────────────
  {
    id: 'metallic-silver',
    name: 'Metallic Silver',
    description: 'Light metallic elegance',
    mode: 'light',
    colors: {
      background: '#F0F1F3',
      foreground: '#1A1D23',
      surface: '#FFFFFF',
      surfaceElevated: '#F7F8FA',
      border: '#D4D7DD',
      input: '#FFFFFF',
      ring: '#6B7280',
      primary: '#6B7280',
      primaryForeground: '#FFFFFF',
      secondary: '#9CA3AF',
      secondaryForeground: '#1A1D23',
      muted: '#F3F4F6',
      mutedForeground: '#6B7280',
      accent: '#F3F4F6',
      accentForeground: '#1A1D23',
      card: '#FFFFFF',
      cardForeground: '#1A1D23',
      popover: '#FFFFFF',
      popoverForeground: '#1A1D23',
      success: '#059669',
      successForeground: '#FFFFFF',
      warning: '#D97706',
      warningForeground: '#FFFFFF',
      danger: '#DC2626',
      dangerForeground: '#FFFFFF',
      info: '#2563EB',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 3. Metallic Blue ──────────────────────────────────────
  {
    id: 'metallic-blue',
    name: 'Metallic Blue',
    description: 'Navy + steel blue accents',
    mode: 'dark',
    colors: {
      background: '#0C1221',
      foreground: '#E8EAF0',
      surface: '#131B2E',
      surfaceElevated: '#1A2440',
      border: '#2A3A5C',
      input: '#1A2440',
      ring: '#6D9ED8',
      primary: '#6D9ED8',
      primaryForeground: '#0C1221',
      secondary: '#4A6FA5',
      secondaryForeground: '#E8EAF0',
      muted: '#1A2440',
      mutedForeground: '#6B7FA0',
      accent: '#1A2440',
      accentForeground: '#B8CCE5',
      card: '#131B2E',
      cardForeground: '#E8EAF0',
      popover: '#131B2E',
      popoverForeground: '#E8EAF0',
      success: '#4CAF7D',
      successForeground: '#FFFFFF',
      warning: '#D6A84F',
      warningForeground: '#FFFFFF',
      danger: '#D66B6B',
      dangerForeground: '#FFFFFF',
      info: '#6D9ED8',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 4. Metallic Graphite ──────────────────────────────────
  {
    id: 'metallic-graphite',
    name: 'Metallic Graphite',
    description: 'Deep charcoal with steel',
    mode: 'dark',
    colors: {
      background: '#121212',
      foreground: '#E5E5E5',
      surface: '#1A1A1A',
      surfaceElevated: '#222222',
      border: '#333333',
      input: '#222222',
      ring: '#9CA3AF',
      primary: '#9CA3AF',
      primaryForeground: '#121212',
      secondary: '#6B7280',
      secondaryForeground: '#E5E5E5',
      muted: '#222222',
      mutedForeground: '#6B7280',
      accent: '#2A2A2A',
      accentForeground: '#D1D5DB',
      card: '#1A1A1A',
      cardForeground: '#E5E5E5',
      popover: '#1A1A1A',
      popoverForeground: '#E5E5E5',
      success: '#4ADE80',
      successForeground: '#121212',
      warning: '#FBBF24',
      warningForeground: '#121212',
      danger: '#F87171',
      dangerForeground: '#121212',
      info: '#60A5FA',
      infoForeground: '#121212',
    },
  },

  // ── 5. Midnight ───────────────────────────────────────────
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep indigo darkness',
    mode: 'dark',
    colors: {
      background: '#0B0D17',
      foreground: '#E8E9F0',
      surface: '#111425',
      surfaceElevated: '#181C33',
      border: '#2D3154',
      input: '#181C33',
      ring: '#818CF8',
      primary: '#818CF8',
      primaryForeground: '#FFFFFF',
      secondary: '#6366F1',
      secondaryForeground: '#E8E9F0',
      muted: '#181C33',
      mutedForeground: '#6B6F8A',
      accent: '#1E2240',
      accentForeground: '#C7C9E0',
      card: '#111425',
      cardForeground: '#E8E9F0',
      popover: '#111425',
      popoverForeground: '#E8E9F0',
      success: '#34D399',
      successForeground: '#0B0D17',
      warning: '#FBBF24',
      warningForeground: '#0B0D17',
      danger: '#FB7185',
      dangerForeground: '#FFFFFF',
      info: '#818CF8',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 6. Slate ──────────────────────────────────────────────
  {
    id: 'slate',
    name: 'Slate',
    description: 'Professional neutral slate',
    mode: 'dark',
    colors: {
      background: '#0F172A',
      foreground: '#F1F5F9',
      surface: '#1E293B',
      surfaceElevated: '#273548',
      border: '#334155',
      input: '#1E293B',
      ring: '#94A3B8',
      primary: '#94A3B8',
      primaryForeground: '#0F172A',
      secondary: '#64748B',
      secondaryForeground: '#F1F5F9',
      muted: '#1E293B',
      mutedForeground: '#64748B',
      accent: '#273548',
      accentForeground: '#CBD5E1',
      card: '#1E293B',
      cardForeground: '#F1F5F9',
      popover: '#1E293B',
      popoverForeground: '#F1F5F9',
      success: '#4ADE80',
      successForeground: '#0F172A',
      warning: '#FCD34D',
      warningForeground: '#0F172A',
      danger: '#F87171',
      dangerForeground: '#FFFFFF',
      info: '#38BDF8',
      infoForeground: '#0F172A',
    },
  },

  // ── 7. Ocean ──────────────────────────────────────────────
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Deep ocean blue',
    mode: 'dark',
    colors: {
      background: '#0A1628',
      foreground: '#E0F2FE',
      surface: '#0F1D32',
      surfaceElevated: '#152540',
      border: '#1E3A5F',
      input: '#152540',
      ring: '#38BDF8',
      primary: '#38BDF8',
      primaryForeground: '#0A1628',
      secondary: '#0EA5E9',
      secondaryForeground: '#E0F2FE',
      muted: '#152540',
      mutedForeground: '#5B8DB8',
      accent: '#1A2E4A',
      accentForeground: '#BAE6FD',
      card: '#0F1D32',
      cardForeground: '#E0F2FE',
      popover: '#0F1D32',
      popoverForeground: '#E0F2FE',
      success: '#34D399',
      successForeground: '#0A1628',
      warning: '#FBBF24',
      warningForeground: '#0A1628',
      danger: '#F87171',
      dangerForeground: '#FFFFFF',
      info: '#38BDF8',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 8. Emerald ────────────────────────────────────────────
  {
    id: 'emerald',
    name: 'Emerald',
    description: 'Rich forest green',
    mode: 'dark',
    colors: {
      background: '#0A1A14',
      foreground: '#E0F5EC',
      surface: '#0F2620',
      surfaceElevated: '#15332A',
      border: '#1E4D3D',
      input: '#15332A',
      ring: '#34D399',
      primary: '#34D399',
      primaryForeground: '#0A1A14',
      secondary: '#10B981',
      secondaryForeground: '#E0F5EC',
      muted: '#15332A',
      mutedForeground: '#5BAF8E',
      accent: '#1A3D30',
      accentForeground: '#A7F3D0',
      card: '#0F2620',
      cardForeground: '#E0F5EC',
      popover: '#0F2620',
      popoverForeground: '#E0F5EC',
      success: '#34D399',
      successForeground: '#0A1A14',
      warning: '#FBBF24',
      warningForeground: '#0A1A14',
      danger: '#F87171',
      dangerForeground: '#FFFFFF',
      info: '#38BDF8',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 9. Royal Purple ───────────────────────────────────────
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    description: 'Rich luxurious purple',
    mode: 'dark',
    colors: {
      background: '#13091F',
      foreground: '#EDE9F6',
      surface: '#1A0F2E',
      surfaceElevated: '#221640',
      border: '#36225C',
      input: '#221640',
      ring: '#A78BFA',
      primary: '#A78BFA',
      primaryForeground: '#13091F',
      secondary: '#8B5CF6',
      secondaryForeground: '#EDE9F6',
      muted: '#221640',
      mutedForeground: '#7C6B9E',
      accent: '#2A1B4A',
      accentForeground: '#DDD6FE',
      card: '#1A0F2E',
      cardForeground: '#EDE9F6',
      popover: '#1A0F2E',
      popoverForeground: '#EDE9F6',
      success: '#34D399',
      successForeground: '#13091F',
      warning: '#FBBF24',
      warningForeground: '#13091F',
      danger: '#FB7185',
      dangerForeground: '#FFFFFF',
      info: '#818CF8',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 10. Clean Light ───────────────────────────────────────
  {
    id: 'clean-light',
    name: 'Clean Light',
    description: 'Crisp and modern light',
    mode: 'light',
    colors: {
      background: '#FFFFFF',
      foreground: '#111827',
      surface: '#F9FAFB',
      surfaceElevated: '#F3F4F6',
      border: '#E5E7EB',
      input: '#FFFFFF',
      ring: '#3B82F6',
      primary: '#3B82F6',
      primaryForeground: '#FFFFFF',
      secondary: '#6B7280',
      secondaryForeground: '#FFFFFF',
      muted: '#F3F4F6',
      mutedForeground: '#6B7280',
      accent: '#EFF6FF',
      accentForeground: '#1D4ED8',
      card: '#FFFFFF',
      cardForeground: '#111827',
      popover: '#FFFFFF',
      popoverForeground: '#111827',
      success: '#059669',
      successForeground: '#FFFFFF',
      warning: '#D97706',
      warningForeground: '#FFFFFF',
      danger: '#DC2626',
      dangerForeground: '#FFFFFF',
      info: '#2563EB',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 11. Minimal Gray ──────────────────────────────────────
  {
    id: 'minimal-gray',
    name: 'Minimal Gray',
    description: 'Clean neutral minimal',
    mode: 'light',
    colors: {
      background: '#FAFAFA',
      foreground: '#171717',
      surface: '#FFFFFF',
      surfaceElevated: '#F5F5F5',
      border: '#E5E5E5',
      input: '#FFFFFF',
      ring: '#525252',
      primary: '#525252',
      primaryForeground: '#FFFFFF',
      secondary: '#737373',
      secondaryForeground: '#FFFFFF',
      muted: '#F5F5F5',
      mutedForeground: '#737373',
      accent: '#F5F5F5',
      accentForeground: '#171717',
      card: '#FFFFFF',
      cardForeground: '#171717',
      popover: '#FFFFFF',
      popoverForeground: '#171717',
      success: '#16A34A',
      successForeground: '#FFFFFF',
      warning: '#CA8A04',
      warningForeground: '#FFFFFF',
      danger: '#DC2626',
      dangerForeground: '#FFFFFF',
      info: '#2563EB',
      infoForeground: '#FFFFFF',
    },
  },

  // ── 12. Professional Blue ─────────────────────────────────
  {
    id: 'professional-blue',
    name: 'Professional Blue',
    description: 'Corporate blue standard',
    mode: 'light',
    colors: {
      background: '#F8FAFC',
      foreground: '#0F172A',
      surface: '#FFFFFF',
      surfaceElevated: '#F1F5F9',
      border: '#CBD5E1',
      input: '#FFFFFF',
      ring: '#1E40AF',
      primary: '#1E40AF',
      primaryForeground: '#FFFFFF',
      secondary: '#3B82F6',
      secondaryForeground: '#FFFFFF',
      muted: '#F1F5F9',
      mutedForeground: '#64748B',
      accent: '#EFF6FF',
      accentForeground: '#1E40AF',
      card: '#FFFFFF',
      cardForeground: '#0F172A',
      popover: '#FFFFFF',
      popoverForeground: '#0F172A',
      success: '#059669',
      successForeground: '#FFFFFF',
      warning: '#D97706',
      warningForeground: '#FFFFFF',
      danger: '#DC2626',
      dangerForeground: '#FFFFFF',
      info: '#1E40AF',
      infoForeground: '#FFFFFF',
    },
  },
];

export const DEFAULT_THEME_ID = 'metallic-dark';

export function getThemeById(id: string): ThemeConfig | undefined {
  return themes.find((t) => t.id === id);
}

export function getDefaultTheme(): ThemeConfig {
  return themes[0];
}
